from __future__ import annotations

import json
from pathlib import Path

import faiss
import pandas as pd

from embeddings import PolicyEmbedder


# ============================================================
# PATHS
# ============================================================

# PolicyLens/
# ├── part1_preprocessing/
# │   └── data/
# │       └── dataset_final_extraction/
# │           └── all_clauses_annotation.csv
# │
# └── part3_retrieval_rag/
#     ├── embeddings.py
#     ├── build_index.py
#     └── data/

PROJECT_ROOT = Path(__file__).resolve().parent.parent

CLAUSES_FILE = (
    PROJECT_ROOT
    / "part1_preprocessing"
    / "data"
    / "dataset_final_extraction"
    / "all_clauses_annotation.csv"
)

OUTPUT_DIR = (
    Path(__file__).resolve().parent
    / "data"
)

INDEX_FILE = OUTPUT_DIR / "policy_index.faiss"
METADATA_FILE = OUTPUT_DIR / "metadata.json"


# ============================================================
# LOAD CLAUSES
# ============================================================

def load_clauses() -> pd.DataFrame:
    """
    Load the structured policy clauses generated by Part 1.
    """

    print("=" * 60)
    print("LOADING POLICY CLAUSES")
    print("=" * 60)

    print(f"Dataset:\n{CLAUSES_FILE}\n")

    if not CLAUSES_FILE.exists():
        raise FileNotFoundError(
            f"\nClause dataset not found:\n{CLAUSES_FILE}\n"
            "Make sure Part 1 has generated "
            "all_clauses_annotation.csv."
        )

    df = pd.read_csv(CLAUSES_FILE)

    print(f"Rows loaded: {len(df)}")

    # Columns that Part 3 actually needs.
    required_columns = [
        "clause_id",
        "policy_id",
        "page_start",
        "page_end",
        "section",
        "subsection",
        "marker",
        "clause_text",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"\nMissing required columns:\n{missing_columns}\n"
            f"Available columns:\n{list(df.columns)}"
        )

    # Remove clauses without usable text.
    df = df.dropna(subset=["clause_text"])

    df["clause_text"] = (
        df["clause_text"]
        .astype(str)
        .str.strip()
    )

    df = df[df["clause_text"] != ""]

    # Reset indexes after filtering.
    df = df.reset_index(drop=True)

    print(f"Usable clauses: {len(df)}")

    return df


# ============================================================
# CREATE METADATA
# ============================================================

def create_metadata(df: pd.DataFrame) -> list[dict]:
    """
    Create metadata corresponding exactly to the FAISS vector order.

    IMPORTANT:
    metadata[i] corresponds to FAISS vector i.
    """

    metadata = []

    for _, row in df.iterrows():

        metadata.append(
            {
                "clause_id": str(row["clause_id"]),

                "policy_id": str(row["policy_id"]),

                "page_start": int(row["page_start"]),

                "page_end": int(row["page_end"]),

                "section": (
                    str(row["section"])
                    if pd.notna(row["section"])
                    else ""
                ),

                "subsection": (
                    str(row["subsection"])
                    if pd.notna(row["subsection"])
                    else ""
                ),

                "marker": (
                    str(row["marker"])
                    if pd.notna(row["marker"])
                    else ""
                ),

                "clause_text": str(row["clause_text"]),
            }
        )

    return metadata


# ============================================================
# BUILD FAISS INDEX
# ============================================================

def build_index() -> None:

    print("\n")
    print("=" * 60)
    print("POLICYLENS RETRIEVAL INDEX BUILDER")
    print("=" * 60)

    # --------------------------------------------------------
    # 1. Create output directory
    # --------------------------------------------------------

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # 2. Load clauses
    # --------------------------------------------------------

    df = load_clauses()

    texts = df["clause_text"].tolist()

    print("\nFirst clause:")
    print(texts[0][:300])

    print("\nLast clause:")
    print(texts[-1][:300])

    # --------------------------------------------------------
    # 3. Load embedding model
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("LOADING EMBEDDING MODEL")
    print("=" * 60)

    embedder = PolicyEmbedder()

    print(f"Model: {embedder.model_name}")
    print(f"Dimension: {embedder.dimension}")

    # --------------------------------------------------------
    # 4. Generate embeddings
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("GENERATING EMBEDDINGS")
    print("=" * 60)

    embeddings = embedder.embed_documents(texts)

    print(
        f"\nEmbedding matrix shape: {embeddings.shape}"
    )

    print(
        f"Embedding dtype: {embeddings.dtype}"
    )

    # Safety check.
    expected_count = len(df)

    if embeddings.shape[0] != expected_count:
        raise ValueError(
            f"Number of embeddings ({embeddings.shape[0]}) "
            f"does not match number of clauses ({expected_count})."
        )

    if embeddings.shape[1] != embedder.dimension:
        raise ValueError(
            f"Embedding dimension mismatch. "
            f"Expected {embedder.dimension}, "
            f"got {embeddings.shape[1]}."
        )

    # --------------------------------------------------------
    # 5. Build FAISS index
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("BUILDING FAISS INDEX")
    print("=" * 60)

    dimension = embeddings.shape[1]

    # BGE-M3 embeddings are already normalized.
    #
    # Inner product between normalized vectors
    # is equivalent to cosine similarity.

    index = faiss.IndexFlatIP(dimension)

    index.add(embeddings)

    print(f"FAISS dimension: {dimension}")
    print(f"Vectors added: {index.ntotal}")

    if index.ntotal != expected_count:
        raise ValueError(
            f"FAISS contains {index.ntotal} vectors, "
            f"but expected {expected_count}."
        )

    # --------------------------------------------------------
    # 6. Create metadata
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("CREATING METADATA")
    print("=" * 60)

    metadata = create_metadata(df)

    print(f"Metadata records: {len(metadata)}")

    if len(metadata) != index.ntotal:
        raise ValueError(
            "Metadata count does not match FAISS vector count."
        )

    # --------------------------------------------------------
    # 7. Save FAISS index
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("SAVING INDEX")
    print("=" * 60)

    faiss.write_index(
        index,
        str(INDEX_FILE)
    )

    print(f"FAISS index saved to:")
    print(INDEX_FILE)

    # --------------------------------------------------------
    # 8. Save metadata
    # --------------------------------------------------------

    with open(
        METADATA_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            metadata,
            file,
            ensure_ascii=False,
            indent=2
        )

    print("\nMetadata saved to:")
    print(METADATA_FILE)

    # --------------------------------------------------------
    # 9. Final validation
    # --------------------------------------------------------

    print("\n")
    print("=" * 60)
    print("FINAL VALIDATION")
    print("=" * 60)

    # Reload FAISS index to make sure it was written correctly.
    loaded_index = faiss.read_index(
        str(INDEX_FILE)
    )

    # Reload metadata.
    with open(
        METADATA_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        loaded_metadata = json.load(file)

    print(
        f"Reloaded FAISS vectors: "
        f"{loaded_index.ntotal}"
    )

    print(
        f"Reloaded metadata records: "
        f"{len(loaded_metadata)}"
    )

    if loaded_index.ntotal != len(loaded_metadata):
        raise ValueError(
            "Final validation failed: "
            "FAISS and metadata counts differ."
        )

    print("\n")
    print("=" * 60)
    print("INDEX BUILD SUCCESSFUL")
    print("=" * 60)

    print(f"\nClauses indexed: {loaded_index.ntotal}")
    print(f"Embedding dimension: {dimension}")
    print(f"FAISS index: {INDEX_FILE}")
    print(f"Metadata: {METADATA_FILE}")


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    build_index()